services:
  chat2api:
    container_name: chat2api-manager
    build:
      context: .
      dockerfile: Dockerfile
    image: chat2api-manager:local
    environment:
      ENV: prod
    ports:
      - "${CHAT2API_PORT:-3040}:3040"
    volumes:
      - ./.chat2api/conf:/app/conf
      - ./.chat2api/logs:/app/logs
    restart: unless-stopped
